# This is a basic workflow to help you get started with Actions

name: Continuous Deployment

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            
            - run: echo "Setting up NodeJs"
            - name: Setup NodeJs
              uses: actions/setup-node@v1
              with:
               node-version: 12.x

            - run: npm install -g surge
            - run: echo "Deploying website"
            - run: surge ./ surge utopian-party.surge.sh --token ${{ secrets.SURGE_TOKEN }} 




          


